:Author: aarushiramesh
:Email: {AuthorEmail}
:Date: 25/04/2020
:Revision: version#
:License: Public Domain

= Project: 4-bit Digital to Analog Convertor

Testing for a 4bit DAC.

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact aarushiramesh https://id.arduino.cc/aarushiramesh

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Quantity
| R1 | 1k Resistor    | 3
| R2 | 2k Resistor    | 5
| A1 | Arduino UNO    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
